SELECT * FROM CART
WHERE USER_ID = 'ff'
;

SELECT * FROM PRODUCT_OPTION;
SELECT * FROM PRODUCT;

SELECT * FROM PRODUCT_OPTION;

UPDATE PRODUCT_OPTION
SET OPTION_COUNT = 10
WHERE OPTION_NO = 2
;

COMMIT;
SELECT C.USER_ID, C.CART_NO, P.PRODUCT_NAME, P.THUMNAIL, P.PRICE, C.QTY, C.QTY*P.PRICE AS TOTAL, O.OPTION_SIZE, P.PRODUCT_NO
FROM CART C, PRODUCT P, PRODUCT_OPTION O
WHERE C.OPTION_NO = O.OPTION_NO
AND O.PRODUCT_NO = P.PRODUCT_NO
AND C.USER_ID = 'ff'
ORDER BY CART_NO DESC
;

DELETE CART
WHERE CART_NO = 100
;

SELECT * FROM CART;

UPDATE CART
SET QTY = 1
WHERE CART_NO = 18
AND USER_ID = 'ff'
;

commit;


SELECT PRICE
FROM CART
WHERE CART_NO = 18
;

	SELECT C.USER_ID, C.CART_NO, P.PRODUCT_NAME, P.THUMNAIL, P.PRICE, C.AMOUNT, C.AMOUNT*P.PRICE AS TOTAL, O.OPTION_SIZE, P.PRODUCT_NO
	FROM CART C, PRODUCT P, PRODUCT_OPTION O
	WHERE C.OPTION_NO = O.OPTION_NO
	AND O.PRODUCT_NO = P.PRODUCT_NO
	AND C.USER_ID = 'ff'
	ORDER BY CART_NO DESC
    ;


DELETE CART
WHERE 1=1
;
COMMIT;


SELECT * FROM LIKE_PRODUCT;

SELECT * FROM CART
RETURN COUNT(*)
;