--BEST ITEM, NEW, 1+1 이벤트는 카테고리가 아님 나중에 지워야 될 듯
INSERT INTO CATEGORY
VALUES (CATEGORY_SEQ.NEXTVAL, 'BESTITEM')
;

INSERT INTO CATEGORY
VALUES (CATEGORY_SEQ.NEXTVAL, 'NEW')
;

INSERT INTO CATEGORY
VALUES (CATEGORY_SEQ.NEXTVAL, '1+1이벤트')
;

INSERT INTO CATEGORY
VALUES (CATEGORY_SEQ.NEXTVAL, 'SETUP')
;

INSERT INTO CATEGORY
VALUES (CATEGORY_SEQ.NEXTVAL, 'OUTER')
;

INSERT INTO CATEGORY
VALUES (CATEGORY_SEQ.NEXTVAL, 'TOP')
;

INSERT INTO CATEGORY
VALUES (CATEGORY_SEQ.NEXTVAL, 'BOTTOM')
;

INSERT INTO CATEGORY
VALUES (CATEGORY_SEQ.NEXTVAL, 'SHOESBAG')
;

INSERT INTO CATEGORY
VALUES (CATEGORY_SEQ.NEXTVAL, 'ACC')
;
