SELECT * FROM PRODUCT_OPTION;

INSERT INTO PRODUCT_OPTION
VALUES (PRODUCT_OPTION_SEQ.NEXTVAL, 1, 'S', 70)
;

INSERT INTO PRODUCT_OPTION
VALUES (PRODUCT_OPTION_SEQ.NEXTVAL, 1, 'M', 70)
;

INSERT INTO PRODUCT_OPTION
VALUES (PRODUCT_OPTION_SEQ.NEXTVAL, 2, 'L', 70)
;

commit;


SELECT *
FROM PRODUCT_OPTION
WHERE PRODUCT_NO = 1
;