
SELECT *
FROM PRODUCT;

SELECT * 
FROM PRODUCT
ORDER BY RATE DESC
;

SELECT * FROM ORDER_MAIN;
SELECT * FROM ORDER_DETAIL;

INSERT INTO ORDER_MAIN
VALUES (ORDER_NO_SEQ.NEXTVAL, 'ff')
;

INSERT INTO ORDER_MAIN
VALUES (ORDER_NO_SEQ.NEXTVAL, 'ff')
;

INSERT INTO ORDER_DETAIL
VALUES (ORDER_DETAIL_KEY_SEQ.NEXTVAL, 1, 1, 1, 30000, '결제완료', SYSDATE-1, 1)
;

INSERT INTO ORDER_DETAIL
VALUES (ORDER_DETAIL_KEY_SEQ.NEXTVAL, 1, 1, 1, 90000, '결제완료', SYSDATE-1, 2)
;


INSERT INTO ORDER_DETAIL
VALUES (ORDER_DETAIL_KEY_SEQ.NEXTVAL, 1, 2, 2, 90000, '결제완료', SYSDATE-1, 3)
;


INSERT INTO ORDER_DETAIL
VALUES (ORDER_DETAIL_KEY_SEQ.NEXTVAL, 1, 1, 6, 90000, '결제완료', SYSDATE-1, 3)
;

INSERT INTO ORDER_DETAIL
VALUES (ORDER_DETAIL_KEY_SEQ.NEXTVAL, 1, 2, 6, 90000, '결제완료', SYSDATE-1, 3)
;


COMMIT;

SELECT * FROM ORDER_DETAIL;

SELECT SUM(AMOUNT) SUM
FROM ORDER_DETAIL
GROUP BY PRODUCT_NO
ORDER BY SUM DESC
;


SELECT P.*
FROM PRODUCT P, (SELECT SUM(AMOUNT) SUM, PRODUCT_NO FROM ORDER_DETAIL GROUP BY PRODUCT_NO) D
WHERE P.PRODUCT_NO = D.PRODUCT_NO
ORDER BY D.SUM DESC
;



SELECT P.*
FROM PRODUCT P, (SELECT SUM(AMOUNT) SUM FROM ORDER_DETAIL GROUP BY PRODUCT_NO ORDER BY SUM DESC) D
WHERE P.PRODUCT_NO = D.PRODUCT_NO
ORDER BY D.SUM
;

SELECT P.*
FROM PRODUCT P, ORDER_DETAIL D
WHERE P.PRODUCT_NO = D.PRODUCT_NO
ORDER BY D.PRODUCT_NO DESC
;

SELECT P.*
FROM PRODUCT P, (SELECT SUM(AMOUNT) SUM, PRODUCT_NO FROM ORDER_DETAIL GROUP BY PRODUCT_NO) D
WHERE P.PRODUCT_NO = D.PRODUCT_NO
AND ROWNUM <= 2
ORDER BY D.SUM DESC
;