SELECT * FROM PRODUCT;

DELETE PRODUCT
WHERE 1=1
;

COMMIT; 

-- SET DEFINE OFF;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '멜루드 1+1 무지티', 30000, 1, 'product_0.jpg', 'product_0.jpg', null)
;

COMMIT;


INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 혜인 SET] BOUCLE SHORT PADDING&BASIC PLEATED MINI SKIRT',
337000, 1, 'product_1.jpg', 'product_1.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 다니엘 SET] CROP SHERPA FLEECE JACKET&TUCK WIDE DENIM PANTS',
263000, 1, 'product_2.jpg', 'product_2.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 해린 SET] CROP VARSITY JACKET&PLAID PLEATS MINI SKIRT',
377000, 1, 'product_3.jpg', 'product_3.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 민지 SET] WAVE LOGO CORDUROY JACKET&WOOL CHECK MINI SKIRT',
358000, 1, 'product_4.jpg', 'product_4.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 민지 SET] SIGNATURE SWEATSHIRTS&A DAY OF US SWEATPANTS',
148000, 1, 'product_5.jpg', 'product_5.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 하니 SET] SIGNATURE HOODIE&A DAY OF US SWEATPANTS',
168000, 1, 'product_6.jpg', 'product_6.jpg', null)
;


INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 해린 SET] SIGNATURE SWEATSHIRTS&FIVETWO STAMP KNIT PANTS',
188000, 1, 'product_7.jpg', 'product_7.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 다니엘 SET] SIGNATURE SWEATSHIRTS&A DAY OF US SWEATPANTS',
148000, 1, 'product_8.jpg', 'product_8.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 혜인 SET] SIGNATURE HOODIE&FIVETWO STAMP KNIT PANTS',
208000, 1, 'product_9.jpg', 'product_9.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 혜인 SET] SIGNATURE HOODIE&FIVETWO STAMP KNIT PANTS',
208000, 1, 'product_10.jpg', 'product_10.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, 'LEATHER DOWN PUFFER JACKET',
328000, 1, 'product_11.jpg', 'product_11.jpg', null)
;

SELECT * FROM PRODUCT;
COMMIT;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 다니엘 SET] CROP SHERPA FLEECE JACKET&TUCK WIDE DENIM PANTS',
263000, 1, 'product_2.jpg', 'product_2.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 해린 SET] CROP VARSITY JACKET&PLAID PLEATS MINI SKIRT',
377000, 1, 'product_3.jpg', 'product_3.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 민지 SET] WAVE LOGO CORDUROY JACKET&WOOL CHECK MINI SKIRT',
358000, 1, 'product_4.jpg', 'product_4.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 민지 SET] SIGNATURE SWEATSHIRTS&A DAY OF US SWEATPANTS',
148000, 1, 'product_5.jpg', 'product_5.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 하니 SET] SIGNATURE HOODIE&A DAY OF US SWEATPANTS',
168000, 1, 'product_6.jpg', 'product_6.jpg', null)
;


INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 해린 SET] SIGNATURE SWEATSHIRTS&FIVETWO STAMP KNIT PANTS',
188000, 1, 'product_7.jpg', 'product_7.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 다니엘 SET] SIGNATURE SWEATSHIRTS&A DAY OF US SWEATPANTS',
148000, 1, 'product_8.jpg', 'product_8.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 혜인 SET] SIGNATURE HOODIE&FIVETWO STAMP KNIT PANTS',
208000, 1, 'product_9.jpg', 'product_9.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, '[뉴진스 혜인 SET] SIGNATURE HOODIE&FIVETWO STAMP KNIT PANTS',
208000, 1, 'product_10.jpg', 'product_10.jpg', null)
;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, 'LEATHER DOWN PUFFER JACKET',
328000, 1, 'product_11.jpg', 'product_11.jpg', null)
;

commit;

select * FROM PRODUCT;

INSERT INTO PRODUCT
VALUES (PRODUCTNO_SEQ.NEXTVAL, 'TESTER',
199900, 1, 'product_11.jpg', 'product_11.jpg', null, '테스트용 상세페이지')
;