SELECT * FROM QA;

SELECT * FROM REVIEW;

SELECT * FROM PRODUCT;

SELECT * FROM USERS;


INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 QA', 'TEST용 QNA 작성 중', 'ff', 'fsaf', SYSDATE, 1)
;

INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 2', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 1)
;

INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 3', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 1)
;

INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 3', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 1)
;

INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 3', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 1)
;

INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 3', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 1)
;

INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 3', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 1)
;

INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 3', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 1)
;

INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 3', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 1)
;

INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 3', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 1)
;

INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 3', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 2)
;
INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 4', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 2)
;
INSERT INTO REVIEW
        (REVIEW_NO, TITLE, CONTENT, USER_ID, USER_NAME, WDATE, PRODUCT_NO)
VALUES (REVIEW_NO_SEQ.NEXTVAL, 'TEST용 REVIEW 5', 'TEST용 REVIEW 작성 중', 'ff', 'fsaf', SYSDATE, 2)
;

commit;

SELECT * FROM REVIEW
ORDER BY REVIEW_NO DESC
;

SELECT O.*
FROM ( SELECT ROWNUM R_NUM, R.*
       FROM (SELECT * FROM REVIEW WHERE PRODUCT_NO = 1 ORDER BY REVIEW_NO DESC) R
     ) O
WHERE R_NUM BETWEEN 1 AND 3
;

UPDATE REVIEW
SET HIT = 0
WHERE 1=1
;

COMMIT;
