

SELECT * FROM LIKE_PRODUCT;


SELECT * 
FROM LIKE_PRODUCT
WHERE USER_ID = 'ff'
AND PRODUCT_NO = 4
;

INSERT INTO LIKE_PRODUCT
        (LIKE_NO, PRODUCT_NO, USER_ID, LDATE)
VALUES (LIKE_NO_SEQ.NEXTVAL, '3', 'ff', SYSDATE)
;
SELECT * FROM PRODUCT;

	SELECT *
	FROM ( SELECT ROWNUM R_NUM, P.*
	       FROM (SELECT * FROM PRODUCT ORDER BY  ) P
	      )
	WHERE CATEGORY_NO = 1
	AND R_NUM BETWEEN 1 AND 3
    ;