INSERT INTO CART
        (CART_NO, OPTION_NO, USER_ID, QTY)
VALUES  (CART_NO_SEQ.NEXTVAL, 1, 'ff', 3)
;

COMMIT;

SELECT * FROM CART;

SELECT * FROM PRODUCT_OPTION;

SELECT OPTION_NO
FROM PRODUCT_OPTION
WHERE PRODUCT_NO = 1
AND OPTION_SIZE = 'S'
;

SELECT OPTION_NO 
FROM PRODUCT_OPTION 
WHERE PRODUCT_NO = 2
AND OPTION_SIZE = 'L'
;

SELECT OPTION_NO
FROM PRODUCT_OPTION
WHERE PRODUCT_NO = :productNo
AND OPTION_SIZE = :productOption
;

SELECT OPTION_NO
FROM PRODUCT_OPTION
WHERE PRODUCT_NO = :productNo
AND OPTION_SIZE = :productOption
;

SELECT OPTION_NO
FROM (SELECT * FROM PRODUCT_OPTION WHERE PRODUCT_NO = 1)
WHERE OPTION_SIZE = 'S'
;

SELECT * FROM CART;

SELECT * FROM PRODUCT;

COMMIT;


SELECT * FROM CART;

