CREATE TABLE USERS (
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) UNIQUE,
    PWD VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    ADDRESS VARCHAR2(30) NOT NULL,
    GRADE VARCHAR2(10)
);

SELECT * FROM USERS;


CREATE TABLE PRODUCT (
    PRODUCT_NO NUMBER PRIMARY KEY,
    
    PRODUCT_NAME VARCHAR2(300) NOT NULL,
    PRICE NUMBER NOT NULL,
    CATEGORY_NO NUMBER ,
    CONTENT VARCHAR2(3000),
    THUMNAIL VARCHAR2(30),
    ORIGINAL_IMG VARCHAR2(30),
    RATE NUMBER
);
-- FOREIGN KEY REFERENCES [테이블명] ([컬럼명])


SELECT * FROM PRODUCT;


CREATE TABLE CATEGORY (
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(20) NOT NULL
);

SELECT * FROM CATEGORY;

-- ALTER TABLE [테이블명] ADD CONSTRAINT [FOREIGN KEY명] FOREIGN KEY ([컬럼명]) REFERENCES [테이블명] ([컬럼명])

ALTER TABLE PRODUCT ADD CONSTRAINT CATEGORY_NO FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY (CATEGORY_NO);


CREATE TABLE PRODUCT_OPTION (
    OPTION_NO NUMBER PRIMARY KEY,
    PRODUCT_NO NUMBER,
    OPTION_SIZE VARCHAR2(10),
    OPTION_COUNT NUMBER(10),
    FOREIGN KEY (PRODUCT_NO)
    REFERENCES PRODUCT (PRODUCT_NO)
);

CREATE SEQUENCE PRODUCTNO_SEQ
MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
;

CREATE SEQUENCE CATEGORY_SEQ
MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
;

CREATE SEQUENCE PRODUCT_OPTION_SEQ
MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
;

CREATE SEQUENCE ORDER_NO_SEQ
MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
;

CREATE SEQUENCE ORDER_DETAIL_KEY_SEQ
MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
;

CREATE SEQUENCE QNA_NO_SEQ
MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
;

CREATE SEQUENCE REVIEW_NO_SEQ
MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
;

CREATE SEQUENCE USER_NO_SEQ
MINVALUE 1 MAXVALUE 9999999999999999999999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
;



SELECT * FROM PRODUCT
WHERE CATEGORY_NO = :1
;

SELECT COUNT(*) 
FROM PRODUCT
WHERE CATEGORY_NO = :1
;


SELECT * FROM CATEGORY;

SELECT CATEGORY_NO
FROM CATEGORY
WHERE CATEGORY_NAME = :NAME
;

SELECT * FROM CATEGORY;

SET DEFINE OFF;


COMMIT;


COMMIT;

SELECT * FROM CATEGORY;
SELECT CATEGORY_NAME
FROM CATEGORY
ORDER BY CATEGORY_NO
;

DELETE CATEGORY
WHERE 1=1
;

SELECT * FROM CATEGORY;

COMMIT;



SELECT * FROM PRODUCT;

INSERT INTO PRODUCT
            (PRODUCTNO_SEQ:NEXTVAL, PRODUCT_NAME, )
;

SELECT CATEGORY_NAME
FROM CATEGORY
ORDER BY CATEGORY_NO


SELECT * FROM PRODUCT
WHERE CATEGORY_NO = 1
;

SELECT * FROM CATEGORY;

SELECT CATEGORY_NO
FROM CATEGORY
WHERE CATEGORY_NAME = 'BESTITEM'
;

SELECT CATEGORY_NO
FROM CATEGORY
WHERE CATEGORY_NAME = :category
;



SELECT ROWNUM R_NUM, P.*
FROM (SELECT * FROM PRODUCT ORDER BY PRODUCT_NO) P
WHERE ROWNUM BETWEEN :{begin} AND :{end}
;

SELECT ROWNUM, *
FROM PRODUCT 
WHERE ROWNUM = 1
ORDER BY PRODUCT_NO
;             

SELECT * FROM PRODUCT
WHERE CATEGORY_NO = 1
;

SELECT *
FROM ( SELECT ROWNUM R_NUM, P.*
       FROM (SELECT * FROM PRODUCT ORDER BY PRODUCT_NO DESC ) P
      )
WHERE CATEGORY_NO = 1
AND R_NUM BETWEEN 0 AND 1
;

SELECT PRODUCTNO_SEQ.CURRVAL FROM DUAL;

